name: Deploy

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v1

    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: "root"
        PORT: 22
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/opt/TorrentSeedr/TorrentSeedr"
   
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: "root"
        key: ${{ secrets.SSHKEY }}
        port: 22
        script: bash /opt/TorrentSeedr/TorrentSeedr/.github/workflows/deployScript.sh ${{ secrets.CONFIG }}
